// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adjectives.sql

package store

import (
	"context"
)

const countAdjectives = `-- name: CountAdjectives :one
SELECT COUNT(*) FROM adjectives
`

func (q *Queries) CountAdjectives(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdjectives)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaleAdjectives = `-- name: DeleteStaleAdjectives :exec
DELETE FROM adjectives
WHERE source = $1::text
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest($2::text[]) AS lemma) run
    WHERE run.lemma = adjectives.lemma
  )
`

type DeleteStaleAdjectivesParams struct {
	Source string   `db:"source" json:"source"`
	Lemmas []string `db:"lemmas" json:"lemmas"`
}

// An anti-join, not <> ALL, which would compare every row with every lemma.
func (q *Queries) DeleteStaleAdjectives(ctx context.Context, arg DeleteStaleAdjectivesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleAdjectives, arg.Source, arg.Lemmas)
	return err
}

const getAdjectiveByLemma = `-- name: GetAdjectiveByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adjectives
WHERE lemma = $1
`

func (q *Queries) GetAdjectiveByLemma(ctx context.Context, lemma string) (Adjective, error) {
	row := q.db.QueryRow(ctx, getAdjectiveByLemma, lemma)
	var i Adjective
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const getAdjectiveDefinitions = `-- name: GetAdjectiveDefinitions :one
SELECT definitions FROM adjectives
WHERE lemma = $1
ORDER BY id
LIMIT 1
`

// Active or not: an old sentence's word still shows its meaning.
func (q *Queries) GetAdjectiveDefinitions(ctx context.Context, lemma string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAdjectiveDefinitions, lemma)
	var definitions []byte
	err := row.Scan(&definitions)
	return definitions, err
}

const getRandomAdjective = `-- name: GetRandomAdjective :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adjectives
WHERE active AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomAdjective(ctx context.Context, commonness float64) (Adjective, error) {
	row := q.db.QueryRow(ctx, getRandomAdjective, commonness)
	var i Adjective
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const lookupAdjective = `-- name: LookupAdjective :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adjectives
WHERE active AND lemma = $1
ORDER BY id
LIMIT 1
`

// A locked word: the floor doesn't apply.
func (q *Queries) LookupAdjective(ctx context.Context, lemma string) (Adjective, error) {
	row := q.db.QueryRow(ctx, lookupAdjective, lemma)
	var i Adjective
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const setAdjectiveFrequencies = `-- name: SetAdjectiveFrequencies :execrows
UPDATE adjectives SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE adjectives.lemma = f.word
`

type SetAdjectiveFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so only lowercase lemmas match.
func (q *Queries) SetAdjectiveFrequencies(ctx context.Context, arg SetAdjectiveFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdjectiveFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdjectives = `-- name: UpsertAdjectives :exec
INSERT INTO adjectives (lemma, definitions, source)
SELECT run.lemma, run.definitions::jsonb, $1::text
FROM (
    SELECT unnest($2::text[]) AS lemma,
           unnest($3::text[]) AS definitions
) run
ON CONFLICT (lemma, source) DO UPDATE SET
    definitions = EXCLUDED.definitions,
    frequency   = NULL
`

type UpsertAdjectivesParams struct {
	Source      string   `db:"source" json:"source"`
	Lemmas      []string `db:"lemmas" json:"lemmas"`
	Definitions []string `db:"definitions" json:"definitions"`
}

// One row per lemma: ingest pools the entries sharing one first, since an
// upsert can't hit the same row twice. Sourced columns are replaced and
// derived ones reset for the later ingest passes. Curated columns
// (active, vote_count) are never written.
func (q *Queries) UpsertAdjectives(ctx context.Context, arg UpsertAdjectivesParams) error {
	_, err := q.db.Exec(ctx, upsertAdjectives, arg.Source, arg.Lemmas, arg.Definitions)
	return err
}
