// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adverbs.sql

package store

import (
	"context"
)

const countAdverbs = `-- name: CountAdverbs :one
SELECT COUNT(*) FROM adverbs
`

func (q *Queries) CountAdverbs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdverbs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaleAdverbs = `-- name: DeleteStaleAdverbs :exec
DELETE FROM adverbs
WHERE source = $1::text
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest($2::text[]) AS lemma) run
    WHERE run.lemma = adverbs.lemma
  )
`

type DeleteStaleAdverbsParams struct {
	Source string   `db:"source" json:"source"`
	Lemmas []string `db:"lemmas" json:"lemmas"`
}

// An anti-join, not <> ALL, which would compare every row with every lemma.
func (q *Queries) DeleteStaleAdverbs(ctx context.Context, arg DeleteStaleAdverbsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleAdverbs, arg.Source, arg.Lemmas)
	return err
}

const getAdverbByLemma = `-- name: GetAdverbByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adverbs
WHERE lemma = $1
`

func (q *Queries) GetAdverbByLemma(ctx context.Context, lemma string) (Adverb, error) {
	row := q.db.QueryRow(ctx, getAdverbByLemma, lemma)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const getAdverbDefinitions = `-- name: GetAdverbDefinitions :one
SELECT definitions FROM adverbs
WHERE lemma = $1
ORDER BY id
LIMIT 1
`

// Active or not: an old sentence's word still shows its meaning.
func (q *Queries) GetAdverbDefinitions(ctx context.Context, lemma string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAdverbDefinitions, lemma)
	var definitions []byte
	err := row.Scan(&definitions)
	return definitions, err
}

const getRandomAdverb = `-- name: GetRandomAdverb :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adverbs
WHERE active AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomAdverb(ctx context.Context, commonness float64) (Adverb, error) {
	row := q.db.QueryRow(ctx, getRandomAdverb, commonness)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const lookupAdverb = `-- name: LookupAdverb :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, definitions FROM adverbs
WHERE active AND lemma = $1
ORDER BY id
LIMIT 1
`

// A locked word: the floor doesn't apply.
func (q *Queries) LookupAdverb(ctx context.Context, lemma string) (Adverb, error) {
	row := q.db.QueryRow(ctx, lookupAdverb, lemma)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Definitions,
	)
	return i, err
}

const setAdverbFrequencies = `-- name: SetAdverbFrequencies :execrows
UPDATE adverbs SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE adverbs.lemma = f.word
`

type SetAdverbFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so only lowercase lemmas match.
func (q *Queries) SetAdverbFrequencies(ctx context.Context, arg SetAdverbFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdverbFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdverbs = `-- name: UpsertAdverbs :exec
INSERT INTO adverbs (lemma, definitions, source)
SELECT run.lemma, run.definitions::jsonb, $1::text
FROM (
    SELECT unnest($2::text[]) AS lemma,
           unnest($3::text[]) AS definitions
) run
ON CONFLICT (lemma, source) DO UPDATE SET
    definitions = EXCLUDED.definitions,
    frequency   = NULL
`

type UpsertAdverbsParams struct {
	Source      string   `db:"source" json:"source"`
	Lemmas      []string `db:"lemmas" json:"lemmas"`
	Definitions []string `db:"definitions" json:"definitions"`
}

// One row per lemma: ingest pools the entries sharing one first, since an
// upsert can't hit the same row twice. Sourced columns are replaced and
// derived ones reset for the later ingest passes. Curated columns
// (active, vote_count) are never written.
func (q *Queries) UpsertAdverbs(ctx context.Context, arg UpsertAdverbsParams) error {
	_, err := q.db.Exec(ctx, upsertAdverbs, arg.Source, arg.Lemmas, arg.Definitions)
	return err
}
