// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adverbs.sql

package store

import (
	"context"
)

const countAdverbs = `-- name: CountAdverbs :one
SELECT COUNT(*) FROM adverbs
`

func (q *Queries) CountAdverbs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdverbs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdverbByLemma = `-- name: GetAdverbByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM adverbs
WHERE lemma = $1
`

func (q *Queries) GetAdverbByLemma(ctx context.Context, lemma string) (Adverb, error) {
	row := q.db.QueryRow(ctx, getAdverbByLemma, lemma)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getRandomAdverb = `-- name: GetRandomAdverb :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM adverbs
WHERE active AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomAdverb(ctx context.Context, commonness float64) (Adverb, error) {
	row := q.db.QueryRow(ctx, getRandomAdverb, commonness)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertAdverb = `-- name: InsertAdverb :exec
INSERT INTO adverbs (lemma, inflections, source)
VALUES ($1, $2, $3)
ON CONFLICT (lemma, source) DO NOTHING
`

type InsertAdverbParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Source      string `db:"source" json:"source"`
}

func (q *Queries) InsertAdverb(ctx context.Context, arg InsertAdverbParams) error {
	_, err := q.db.Exec(ctx, insertAdverb, arg.Lemma, arg.Inflections, arg.Source)
	return err
}

const lookupAdverb = `-- name: LookupAdverb :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time FROM adverbs
WHERE active AND lemma = $1
ORDER BY id
LIMIT 1
`

// A locked word: the floor doesn't apply.
func (q *Queries) LookupAdverb(ctx context.Context, lemma string) (Adverb, error) {
	row := q.db.QueryRow(ctx, lookupAdverb, lemma)
	var i Adverb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const setAdverbFrequencies = `-- name: SetAdverbFrequencies :execrows
UPDATE adverbs SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE adverbs.lemma = f.word
`

type SetAdverbFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so only lowercase lemmas match.
func (q *Queries) SetAdverbFrequencies(ctx context.Context, arg SetAdverbFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdverbFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const truncateAdverbs = `-- name: TruncateAdverbs :exec
TRUNCATE adverbs RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateAdverbs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAdverbs)
	return err
}
