// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conjunctions.sql

package store

import (
	"context"
)

const getRandomConjunction = `-- name: GetRandomConjunction :one
SELECT id, lemma, type, active, joins_nps FROM conjunctions
WHERE active
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomConjunction(ctx context.Context) (Conjunction, error) {
	row := q.db.QueryRow(ctx, getRandomConjunction)
	var i Conjunction
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Type,
		&i.Active,
		&i.JoinsNps,
	)
	return i, err
}

const getRandomConjunctionOfType = `-- name: GetRandomConjunctionOfType :one
SELECT id, lemma, type, active, joins_nps FROM conjunctions
WHERE active AND type = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomConjunctionOfType(ctx context.Context, type_ string) (Conjunction, error) {
	row := q.db.QueryRow(ctx, getRandomConjunctionOfType, type_)
	var i Conjunction
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Type,
		&i.Active,
		&i.JoinsNps,
	)
	return i, err
}

const getRandomNPConjunction = `-- name: GetRandomNPConjunction :one
SELECT id, lemma, type, active, joins_nps FROM conjunctions
WHERE active AND joins_nps
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomNPConjunction(ctx context.Context) (Conjunction, error) {
	row := q.db.QueryRow(ctx, getRandomNPConjunction)
	var i Conjunction
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Type,
		&i.Active,
		&i.JoinsNps,
	)
	return i, err
}

const insertConjunction = `-- name: InsertConjunction :exec
INSERT INTO conjunctions (lemma, type, joins_nps)
VALUES ($1, $2, $3)
`

type InsertConjunctionParams struct {
	Lemma    string `db:"lemma" json:"lemma"`
	Type     string `db:"type" json:"type"`
	JoinsNps bool   `db:"joins_nps" json:"joins_nps"`
}

func (q *Queries) InsertConjunction(ctx context.Context, arg InsertConjunctionParams) error {
	_, err := q.db.Exec(ctx, insertConjunction, arg.Lemma, arg.Type, arg.JoinsNps)
	return err
}

const listConjunctions = `-- name: ListConjunctions :many
SELECT id, lemma, type, active, joins_nps FROM conjunctions
ORDER BY lemma, type
`

func (q *Queries) ListConjunctions(ctx context.Context) ([]Conjunction, error) {
	rows, err := q.db.Query(ctx, listConjunctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conjunction
	for rows.Next() {
		var i Conjunction
		if err := rows.Scan(
			&i.ID,
			&i.Lemma,
			&i.Type,
			&i.Active,
			&i.JoinsNps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupConjunction = `-- name: LookupConjunction :one
SELECT id, lemma, type, active, joins_nps FROM conjunctions
WHERE active AND lemma = $1 AND ($2::text = '' OR type = $2::text)
  AND (joins_nps OR NOT $3::bool)
ORDER BY id
LIMIT 1
`

type LookupConjunctionParams struct {
	Lemma    string `db:"lemma" json:"lemma"`
	Type     string `db:"type" json:"type"`
	JoinsNps bool   `db:"joins_nps" json:"joins_nps"`
}

// An empty type matches either; joins_nps requires a conjunction that can
// join noun phrases.
func (q *Queries) LookupConjunction(ctx context.Context, arg LookupConjunctionParams) (Conjunction, error) {
	row := q.db.QueryRow(ctx, lookupConjunction, arg.Lemma, arg.Type, arg.JoinsNps)
	var i Conjunction
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Type,
		&i.Active,
		&i.JoinsNps,
	)
	return i, err
}

const truncateConjunctions = `-- name: TruncateConjunctions :exec
TRUNCATE conjunctions RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateConjunctions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateConjunctions)
	return err
}
