// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFlag = `-- name: InsertFlag :one
INSERT INTO flags (sentence_id, word_index, lemma, pos, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertFlagParams struct {
	SentenceID string      `db:"sentence_id" json:"sentence_id"`
	WordIndex  pgtype.Int4 `db:"word_index" json:"word_index"`
	Lemma      pgtype.Text `db:"lemma" json:"lemma"`
	Pos        pgtype.Text `db:"pos" json:"pos"`
	Comment    string      `db:"comment" json:"comment"`
}

func (q *Queries) InsertFlag(ctx context.Context, arg InsertFlagParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFlag,
		arg.SentenceID,
		arg.WordIndex,
		arg.Lemma,
		arg.Pos,
		arg.Comment,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
