// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Adjective struct {
	ID          int64              `db:"id" json:"id"`
	Lemma       string             `db:"lemma" json:"lemma"`
	Inflections []byte             `db:"inflections" json:"inflections"`
	Source      string             `db:"source" json:"source"`
	SourceID    pgtype.Text        `db:"source_id" json:"source_id"`
	Register    pgtype.Text        `db:"register" json:"register"`
	Frequency   pgtype.Numeric     `db:"frequency" json:"frequency"`
	Active      bool               `db:"active" json:"active"`
	VoteCount   int32              `db:"vote_count" json:"vote_count"`
	CreateTime  pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime  pgtype.Timestamptz `db:"update_time" json:"update_time"`
	Definitions []byte             `db:"definitions" json:"definitions"`
}

type Adverb struct {
	ID          int64              `db:"id" json:"id"`
	Lemma       string             `db:"lemma" json:"lemma"`
	Inflections []byte             `db:"inflections" json:"inflections"`
	Source      string             `db:"source" json:"source"`
	SourceID    pgtype.Text        `db:"source_id" json:"source_id"`
	Register    pgtype.Text        `db:"register" json:"register"`
	Frequency   pgtype.Numeric     `db:"frequency" json:"frequency"`
	Active      bool               `db:"active" json:"active"`
	VoteCount   int32              `db:"vote_count" json:"vote_count"`
	CreateTime  pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime  pgtype.Timestamptz `db:"update_time" json:"update_time"`
	Definitions []byte             `db:"definitions" json:"definitions"`
}

type Conjunction struct {
	ID       int64  `db:"id" json:"id"`
	Lemma    string `db:"lemma" json:"lemma"`
	Type     string `db:"type" json:"type"`
	Active   bool   `db:"active" json:"active"`
	JoinsNps bool   `db:"joins_nps" json:"joins_nps"`
}

type Determiner struct {
	ID     int64  `db:"id" json:"id"`
	Lemma  string `db:"lemma" json:"lemma"`
	Type   string `db:"type" json:"type"`
	Number string `db:"number" json:"number"`
	Active bool   `db:"active" json:"active"`
}

type Flag struct {
	ID         int64              `db:"id" json:"id"`
	SentenceID string             `db:"sentence_id" json:"sentence_id"`
	WordIndex  pgtype.Int4        `db:"word_index" json:"word_index"`
	Lemma      pgtype.Text        `db:"lemma" json:"lemma"`
	Pos        pgtype.Text        `db:"pos" json:"pos"`
	Comment    string             `db:"comment" json:"comment"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Noun struct {
	ID             int64              `db:"id" json:"id"`
	Lemma          string             `db:"lemma" json:"lemma"`
	Inflections    []byte             `db:"inflections" json:"inflections"`
	Source         string             `db:"source" json:"source"`
	SourceID       pgtype.Text        `db:"source_id" json:"source_id"`
	Register       pgtype.Text        `db:"register" json:"register"`
	Frequency      pgtype.Numeric     `db:"frequency" json:"frequency"`
	Active         bool               `db:"active" json:"active"`
	VoteCount      int32              `db:"vote_count" json:"vote_count"`
	CreateTime     pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime     pgtype.Timestamptz `db:"update_time" json:"update_time"`
	PluralGuess    bool               `db:"plural_guess" json:"plural_guess"`
	Definitions    []byte             `db:"definitions" json:"definitions"`
	PluralOverride pgtype.Bool        `db:"plural_override" json:"plural_override"`
	Plural         bool               `db:"plural" json:"plural"`
}

type Preposition struct {
	ID     int64  `db:"id" json:"id"`
	Lemma  string `db:"lemma" json:"lemma"`
	Active bool   `db:"active" json:"active"`
}

type Pronoun struct {
	ID     int64  `db:"id" json:"id"`
	Lemma  string `db:"lemma" json:"lemma"`
	Case   string `db:"case_" json:"case_"`
	Person int16  `db:"person" json:"person"`
	Number string `db:"number" json:"number"`
	Gender string `db:"gender" json:"gender"`
	Active bool   `db:"active" json:"active"`
}

type Sentence struct {
	ID         string             `db:"id" json:"id"`
	Text       string             `db:"text" json:"text"`
	Tree       []byte             `db:"tree" json:"tree"`
	Commonness pgtype.Numeric     `db:"commonness" json:"commonness"`
	StarCount  int32              `db:"star_count" json:"star_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Origin     string             `db:"origin" json:"origin"`
}

type Star struct {
	SentenceID string             `db:"sentence_id" json:"sentence_id"`
	Voter      string             `db:"voter" json:"voter"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID         int64              `db:"id" json:"id"`
	Username   string             `db:"username" json:"username"`
	IsAdmin    bool               `db:"is_admin" json:"is_admin"`
	CreateTime pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime pgtype.Timestamptz `db:"update_time" json:"update_time"`
}

type Verb struct {
	ID          int64              `db:"id" json:"id"`
	Lemma       string             `db:"lemma" json:"lemma"`
	Inflections []byte             `db:"inflections" json:"inflections"`
	Frames      []byte             `db:"frames" json:"frames"`
	Source      string             `db:"source" json:"source"`
	SourceID    pgtype.Text        `db:"source_id" json:"source_id"`
	Register    pgtype.Text        `db:"register" json:"register"`
	Frequency   pgtype.Numeric     `db:"frequency" json:"frequency"`
	Active      bool               `db:"active" json:"active"`
	VoteCount   int32              `db:"vote_count" json:"vote_count"`
	CreateTime  pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime  pgtype.Timestamptz `db:"update_time" json:"update_time"`
	Separable   bool               `db:"separable" json:"separable"`
	Definitions []byte             `db:"definitions" json:"definitions"`
}
