// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nouns.sql

package store

import (
	"context"
)

const countNouns = `-- name: CountNouns :one
SELECT COUNT(*) FROM nouns
`

func (q *Queries) CountNouns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNouns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNounByLemma = `-- name: GetNounByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural, definitions FROM nouns
WHERE lemma = $1
`

func (q *Queries) GetNounByLemma(ctx context.Context, lemma string) (Noun, error) {
	row := q.db.QueryRow(ctx, getNounByLemma, lemma)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
		&i.Definitions,
	)
	return i, err
}

const getNounDefinitions = `-- name: GetNounDefinitions :one
SELECT definitions FROM nouns
WHERE lemma = $1
ORDER BY id
LIMIT 1
`

// Active or not: an old sentence's word still shows its meaning.
func (q *Queries) GetNounDefinitions(ctx context.Context, lemma string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getNounDefinitions, lemma)
	var definitions []byte
	err := row.Scan(&definitions)
	return definitions, err
}

const getRandomNoun = `-- name: GetRandomNoun :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural, definitions FROM nouns
WHERE active AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomNoun(ctx context.Context, commonness float64) (Noun, error) {
	row := q.db.QueryRow(ctx, getRandomNoun, commonness)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
		&i.Definitions,
	)
	return i, err
}

const getRandomSingularNoun = `-- name: GetRandomSingularNoun :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural, definitions FROM nouns
WHERE active AND NOT plural AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

// For a locked singular determiner, which can't go with "Rastas".
func (q *Queries) GetRandomSingularNoun(ctx context.Context, commonness float64) (Noun, error) {
	row := q.db.QueryRow(ctx, getRandomSingularNoun, commonness)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
		&i.Definitions,
	)
	return i, err
}

const insertNoun = `-- name: InsertNoun :exec
INSERT INTO nouns (lemma, inflections, definitions, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (lemma, source) DO UPDATE SET definitions = nouns.definitions || EXCLUDED.definitions
`

type InsertNounParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Definitions []byte `db:"definitions" json:"definitions"`
	Source      string `db:"source" json:"source"`
}

// OEWN entries that share a lemma pool their definitions.
func (q *Queries) InsertNoun(ctx context.Context, arg InsertNounParams) error {
	_, err := q.db.Exec(ctx, insertNoun,
		arg.Lemma,
		arg.Inflections,
		arg.Definitions,
		arg.Source,
	)
	return err
}

const lookupNoun = `-- name: LookupNoun :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural, definitions FROM nouns
WHERE active AND lemma = $1
ORDER BY id
LIMIT 1
`

// A locked word: the floor doesn't apply.
func (q *Queries) LookupNoun(ctx context.Context, lemma string) (Noun, error) {
	row := q.db.QueryRow(ctx, lookupNoun, lemma)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
		&i.Definitions,
	)
	return i, err
}

const markPluralNouns = `-- name: MarkPluralNouns :execrows
UPDATE nouns p SET plural = TRUE
WHERE p.lemma ~ 's$'
  AND length(p.lemma) > 3
  AND p.lemma !~ '(ss|us|is)$'
  AND EXISTS (
    SELECT 1 FROM nouns n
    WHERE n.lemma = left(p.lemma, -1)
       OR (p.lemma ~ 'es$' AND n.lemma = left(p.lemma, -2))
  )
`

// A lemma is plural if it ends in -s and its singular (minus -s, or minus
// -es) is also a lemma ("Rastas"/"Rasta", "eyeglasses"/"eyeglass"). Short
// words and -ss/-us/-is endings ("Ms", "Mass", "Pus") are left singular.
func (q *Queries) MarkPluralNouns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markPluralNouns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNounFrequencies = `-- name: SetNounFrequencies :execrows
UPDATE nouns SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE nouns.lemma = f.word
`

type SetNounFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so only lowercase lemmas match.
func (q *Queries) SetNounFrequencies(ctx context.Context, arg SetNounFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNounFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProperNounFrequencies = `-- name: SetProperNounFrequencies :execrows
UPDATE nouns SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE nouns.lemma <> lower(nouns.lemma) AND lower(nouns.lemma) = f.word
`

type SetProperNounFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so a capitalized lemma ("America") matches its
// lowercase form. Only name frequencies go here, so the element "In" doesn't
// pick up the preposition's.
func (q *Queries) SetProperNounFrequencies(ctx context.Context, arg SetProperNounFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProperNounFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const truncateNouns = `-- name: TruncateNouns :exec
TRUNCATE nouns RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateNouns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateNouns)
	return err
}
