// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// One statement, so star_count and stars change together. Starring twice
	// inserts nothing and adds 0. An unknown sentence fails the foreign key.
	AddStar(ctx context.Context, arg AddStarParams) (int32, error)
	CountAdjectives(ctx context.Context) (int64, error)
	CountAdverbs(ctx context.Context) (int64, error)
	CountNouns(ctx context.Context) (int64, error)
	CountVerbs(ctx context.Context) (int64, error)
	GetAdjectiveByLemma(ctx context.Context, lemma string) (Adjective, error)
	GetAdverbByLemma(ctx context.Context, lemma string) (Adverb, error)
	GetNounByLemma(ctx context.Context, lemma string) (Noun, error)
	GetRandomAdjective(ctx context.Context, commonness float64) (Adjective, error)
	GetRandomAdverb(ctx context.Context, commonness float64) (Adverb, error)
	GetRandomConjunction(ctx context.Context) (Conjunction, error)
	GetRandomConjunctionOfType(ctx context.Context, type_ string) (Conjunction, error)
	GetRandomDeterminer(ctx context.Context) (Determiner, error)
	GetRandomDeterminerWithNumber(ctx context.Context, numbers []string) (Determiner, error)
	GetRandomNPConjunction(ctx context.Context) (Conjunction, error)
	GetRandomNoun(ctx context.Context, commonness float64) (Noun, error)
	GetRandomPreposition(ctx context.Context) (Preposition, error)
	// An empty gender matches any.
	GetRandomPronounWithAgreement(ctx context.Context, arg GetRandomPronounWithAgreementParams) (Pronoun, error)
	GetRandomPronounWithCase(ctx context.Context, case_ string) (Pronoun, error)
	// For a locked singular determiner, which can't go with "Rastas".
	GetRandomSingularNoun(ctx context.Context, commonness float64) (Noun, error)
	GetRandomVerb(ctx context.Context, commonness float64) (Verb, error)
	GetRandomVerbWithFrame(ctx context.Context, arg GetRandomVerbWithFrameParams) (Verb, error)
	GetSentence(ctx context.Context, id string) (Sentence, error)
	GetVerbByLemma(ctx context.Context, lemma string) (Verb, error)
	InsertAdjective(ctx context.Context, arg InsertAdjectiveParams) error
	InsertAdverb(ctx context.Context, arg InsertAdverbParams) error
	InsertConjunction(ctx context.Context, arg InsertConjunctionParams) error
	InsertDeterminer(ctx context.Context, arg InsertDeterminerParams) error
	InsertFlag(ctx context.Context, arg InsertFlagParams) (int64, error)
	InsertNoun(ctx context.Context, arg InsertNounParams) error
	InsertPreposition(ctx context.Context, lemma string) error
	InsertPronoun(ctx context.Context, arg InsertPronounParams) error
	InsertSentence(ctx context.Context, arg InsertSentenceParams) (Sentence, error)
	InsertVerb(ctx context.Context, arg InsertVerbParams) error
	ListConjunctions(ctx context.Context) ([]Conjunction, error)
	ListDeterminers(ctx context.Context) ([]Determiner, error)
	ListFlaggedWords(ctx context.Context, arg ListFlaggedWordsParams) ([]ListFlaggedWordsRow, error)
	ListFlags(ctx context.Context, arg ListFlagsParams) ([]ListFlagsRow, error)
	ListPrepositions(ctx context.Context) ([]Preposition, error)
	ListPronouns(ctx context.Context) ([]Pronoun, error)
	ListSentences(ctx context.Context, arg ListSentencesParams) ([]Sentence, error)
	ListStarredSentences(ctx context.Context, arg ListStarredSentencesParams) ([]Sentence, error)
	// A locked word: the floor doesn't apply.
	LookupAdjective(ctx context.Context, lemma string) (Adjective, error)
	// A locked word: the floor doesn't apply.
	LookupAdverb(ctx context.Context, lemma string) (Adverb, error)
	// An empty type matches either; joins_nps requires a conjunction that can
	// join noun phrases.
	LookupConjunction(ctx context.Context, arg LookupConjunctionParams) (Conjunction, error)
	LookupDeterminer(ctx context.Context, lemma string) (Determiner, error)
	// A locked word: the floor doesn't apply.
	LookupNoun(ctx context.Context, lemma string) (Noun, error)
	LookupPreposition(ctx context.Context, lemma string) (Preposition, error)
	// "you" is singular and plural, so either can come back.
	LookupPronoun(ctx context.Context, arg LookupPronounParams) (Pronoun, error)
	// A locked word: the floor doesn't apply. An empty frame matches any verb.
	LookupVerb(ctx context.Context, arg LookupVerbParams) (Verb, error)
	// A lemma is plural if it ends in -s and its singular (minus -s, or minus
	// -es) is also a lemma ("Rastas"/"Rasta", "eyeglasses"/"eyeglass"). Short
	// words and -ss/-us/-is endings ("Ms", "Mass", "Pus") are left singular.
	MarkPluralNouns(ctx context.Context) (int64, error)
	// An unknown sentence returns no rows.
	RemoveStar(ctx context.Context, arg RemoveStarParams) (int32, error)
	// Words are lowercase, so only lowercase lemmas match.
	SetAdjectiveFrequencies(ctx context.Context, arg SetAdjectiveFrequenciesParams) (int64, error)
	// Words are lowercase, so only lowercase lemmas match.
	SetAdverbFrequencies(ctx context.Context, arg SetAdverbFrequenciesParams) (int64, error)
	// Words are lowercase, so only lowercase lemmas match.
	SetNounFrequencies(ctx context.Context, arg SetNounFrequenciesParams) (int64, error)
	// Words are lowercase, so a capitalized lemma ("America") matches its
	// lowercase form. Only name frequencies go here, so the element "In" doesn't
	// pick up the preposition's.
	SetProperNounFrequencies(ctx context.Context, arg SetProperNounFrequenciesParams) (int64, error)
	SetSeparableVerbs(ctx context.Context, lemmas []string) (int64, error)
	// Words are lowercase, so only lowercase lemmas match.
	SetVerbFrequencies(ctx context.Context, arg SetVerbFrequenciesParams) (int64, error)
	TruncateAdjectives(ctx context.Context) error
	TruncateAdverbs(ctx context.Context) error
	TruncateConjunctions(ctx context.Context) error
	TruncateDeterminers(ctx context.Context) error
	TruncateNouns(ctx context.Context) error
	TruncatePrepositions(ctx context.Context) error
	TruncatePronouns(ctx context.Context) error
	TruncateVerbs(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
