// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentences.sql

package store

import (
	"context"
)

const getSentence = `-- name: GetSentence :one
SELECT id, text, tree, commonness, star_count, created_at FROM sentences
WHERE id = $1
`

func (q *Queries) GetSentence(ctx context.Context, id string) (Sentence, error) {
	row := q.db.QueryRow(ctx, getSentence, id)
	var i Sentence
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Tree,
		&i.Commonness,
		&i.StarCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertSentence = `-- name: InsertSentence :one
INSERT INTO sentences (id, text, tree, commonness)
VALUES ($1, $2, $3, $4::float8)
RETURNING id, text, tree, commonness, star_count, created_at
`

type InsertSentenceParams struct {
	ID         string  `db:"id" json:"id"`
	Text       string  `db:"text" json:"text"`
	Tree       []byte  `db:"tree" json:"tree"`
	Commonness float64 `db:"commonness" json:"commonness"`
}

func (q *Queries) InsertSentence(ctx context.Context, arg InsertSentenceParams) (Sentence, error) {
	row := q.db.QueryRow(ctx, insertSentence,
		arg.ID,
		arg.Text,
		arg.Tree,
		arg.Commonness,
	)
	var i Sentence
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Tree,
		&i.Commonness,
		&i.StarCount,
		&i.CreatedAt,
	)
	return i, err
}

const listSentences = `-- name: ListSentences :many
SELECT id, text, tree, commonness, star_count, created_at FROM sentences
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListSentencesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListSentences(ctx context.Context, arg ListSentencesParams) ([]Sentence, error) {
	rows, err := q.db.Query(ctx, listSentences, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sentence
	for rows.Next() {
		var i Sentence
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Tree,
			&i.Commonness,
			&i.StarCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
