// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stars.sql

package store

import (
	"context"
)

const addStar = `-- name: AddStar :one
WITH added AS (
    INSERT INTO stars (sentence_id, voter)
    VALUES ($1, $2)
    ON CONFLICT DO NOTHING
    RETURNING 1
)
UPDATE sentences SET star_count = star_count + (SELECT count(*) FROM added)
WHERE id = $1
RETURNING star_count
`

type AddStarParams struct {
	SentenceID string `db:"sentence_id" json:"sentence_id"`
	Voter      string `db:"voter" json:"voter"`
}

// One statement, so star_count and stars change together. Starring twice
// inserts nothing and adds 0. An unknown sentence fails the foreign key.
func (q *Queries) AddStar(ctx context.Context, arg AddStarParams) (int32, error) {
	row := q.db.QueryRow(ctx, addStar, arg.SentenceID, arg.Voter)
	var star_count int32
	err := row.Scan(&star_count)
	return star_count, err
}

const listStarredSentences = `-- name: ListStarredSentences :many
SELECT sentences.id, sentences.text, sentences.tree, sentences.commonness, sentences.star_count, sentences.created_at, sentences.origin FROM sentences
JOIN stars ON stars.sentence_id = sentences.id
WHERE stars.voter = $1
ORDER BY stars.created_at DESC, sentences.id DESC
LIMIT $3 OFFSET $2
`

type ListStarredSentencesParams struct {
	Voter      string `db:"voter" json:"voter"`
	PageOffset int32  `db:"page_offset" json:"page_offset"`
	PageLimit  int32  `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListStarredSentences(ctx context.Context, arg ListStarredSentencesParams) ([]Sentence, error) {
	rows, err := q.db.Query(ctx, listStarredSentences, arg.Voter, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sentence
	for rows.Next() {
		var i Sentence
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Tree,
			&i.Commonness,
			&i.StarCount,
			&i.CreatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStar = `-- name: RemoveStar :one
WITH removed AS (
    DELETE FROM stars
    WHERE sentence_id = $1 AND voter = $2
    RETURNING 1
)
UPDATE sentences SET star_count = star_count - (SELECT count(*) FROM removed)
WHERE id = $1
RETURNING star_count
`

type RemoveStarParams struct {
	SentenceID string `db:"sentence_id" json:"sentence_id"`
	Voter      string `db:"voter" json:"voter"`
}

// An unknown sentence returns no rows.
func (q *Queries) RemoveStar(ctx context.Context, arg RemoveStarParams) (int32, error) {
	row := q.db.QueryRow(ctx, removeStar, arg.SentenceID, arg.Voter)
	var star_count int32
	err := row.Scan(&star_count)
	return star_count, err
}
