// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verbs.sql

package store

import (
	"context"
)

const countVerbs = `-- name: CountVerbs :one
SELECT COUNT(*) FROM verbs
`

func (q *Queries) CountVerbs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVerbs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRandomVerb = `-- name: GetRandomVerb :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time, separable, definitions FROM verbs
WHERE active AND coalesce(frequency, 0) >= $1::float8
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomVerb(ctx context.Context, commonness float64) (Verb, error) {
	row := q.db.QueryRow(ctx, getRandomVerb, commonness)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Separable,
		&i.Definitions,
	)
	return i, err
}

const getRandomVerbWithFrame = `-- name: GetRandomVerbWithFrame :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time, separable, definitions FROM verbs
WHERE active AND frames ? $1::text
  AND coalesce(frequency, 0) >= $2::float8
ORDER BY random()
LIMIT 1
`

type GetRandomVerbWithFrameParams struct {
	Frame      string  `db:"frame" json:"frame"`
	Commonness float64 `db:"commonness" json:"commonness"`
}

func (q *Queries) GetRandomVerbWithFrame(ctx context.Context, arg GetRandomVerbWithFrameParams) (Verb, error) {
	row := q.db.QueryRow(ctx, getRandomVerbWithFrame, arg.Frame, arg.Commonness)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Separable,
		&i.Definitions,
	)
	return i, err
}

const getVerbByLemma = `-- name: GetVerbByLemma :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time, separable, definitions FROM verbs
WHERE lemma = $1
`

func (q *Queries) GetVerbByLemma(ctx context.Context, lemma string) (Verb, error) {
	row := q.db.QueryRow(ctx, getVerbByLemma, lemma)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Separable,
		&i.Definitions,
	)
	return i, err
}

const getVerbDefinitions = `-- name: GetVerbDefinitions :one
SELECT definitions FROM verbs
WHERE lemma = $1
ORDER BY id
LIMIT 1
`

// Active or not: an old sentence's word still shows its meaning.
func (q *Queries) GetVerbDefinitions(ctx context.Context, lemma string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getVerbDefinitions, lemma)
	var definitions []byte
	err := row.Scan(&definitions)
	return definitions, err
}

const insertVerb = `-- name: InsertVerb :exec
INSERT INTO verbs (lemma, inflections, frames, definitions, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (lemma, source) DO UPDATE SET definitions = verbs.definitions || EXCLUDED.definitions
`

type InsertVerbParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Frames      []byte `db:"frames" json:"frames"`
	Definitions []byte `db:"definitions" json:"definitions"`
	Source      string `db:"source" json:"source"`
}

// OEWN entries that share a lemma pool their definitions; frames come from
// the first.
func (q *Queries) InsertVerb(ctx context.Context, arg InsertVerbParams) error {
	_, err := q.db.Exec(ctx, insertVerb,
		arg.Lemma,
		arg.Inflections,
		arg.Frames,
		arg.Definitions,
		arg.Source,
	)
	return err
}

const lookupVerb = `-- name: LookupVerb :one
SELECT id, lemma, inflections, frames, source, source_id, register, frequency, active, vote_count, create_time, update_time, separable, definitions FROM verbs
WHERE active AND lemma = $1 AND ($2::text = '' OR frames ? $2::text)
ORDER BY id
LIMIT 1
`

type LookupVerbParams struct {
	Lemma string `db:"lemma" json:"lemma"`
	Frame string `db:"frame" json:"frame"`
}

// A locked word: the floor doesn't apply. An empty frame matches any verb.
func (q *Queries) LookupVerb(ctx context.Context, arg LookupVerbParams) (Verb, error) {
	row := q.db.QueryRow(ctx, lookupVerb, arg.Lemma, arg.Frame)
	var i Verb
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Frames,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Separable,
		&i.Definitions,
	)
	return i, err
}

const setSeparableVerbs = `-- name: SetSeparableVerbs :execrows
UPDATE verbs SET separable = TRUE
WHERE lemma = ANY($1::text[])
`

func (q *Queries) SetSeparableVerbs(ctx context.Context, lemmas []string) (int64, error) {
	result, err := q.db.Exec(ctx, setSeparableVerbs, lemmas)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVerbFrequencies = `-- name: SetVerbFrequencies :execrows
UPDATE verbs SET frequency = round(f.zipf::numeric, 2)
FROM (SELECT unnest($1::text[]) AS word, unnest($2::float8[]) AS zipf) f
WHERE verbs.lemma = f.word
`

type SetVerbFrequenciesParams struct {
	Words []string  `db:"words" json:"words"`
	Zipfs []float64 `db:"zipfs" json:"zipfs"`
}

// Words are lowercase, so only lowercase lemmas match.
func (q *Queries) SetVerbFrequencies(ctx context.Context, arg SetVerbFrequenciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVerbFrequencies, arg.Words, arg.Zipfs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const truncateVerbs = `-- name: TruncateVerbs :exec
TRUNCATE verbs RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateVerbs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateVerbs)
	return err
}
