// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conjunctions.sql

package store

import (
	"context"
)

const getRandomConjunction = `-- name: GetRandomConjunction :one
SELECT id, lemma, type, active FROM conjunctions
WHERE active
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomConjunction(ctx context.Context) (Conjunction, error) {
	row := q.db.QueryRow(ctx, getRandomConjunction)
	var i Conjunction
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Type,
		&i.Active,
	)
	return i, err
}

const insertConjunction = `-- name: InsertConjunction :exec
INSERT INTO conjunctions (lemma, type)
VALUES ($1, $2)
`

type InsertConjunctionParams struct {
	Lemma string `db:"lemma" json:"lemma"`
	Type  string `db:"type" json:"type"`
}

func (q *Queries) InsertConjunction(ctx context.Context, arg InsertConjunctionParams) error {
	_, err := q.db.Exec(ctx, insertConjunction, arg.Lemma, arg.Type)
	return err
}

const listConjunctions = `-- name: ListConjunctions :many
SELECT id, lemma, type, active FROM conjunctions
ORDER BY lemma, type
`

func (q *Queries) ListConjunctions(ctx context.Context) ([]Conjunction, error) {
	rows, err := q.db.Query(ctx, listConjunctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conjunction
	for rows.Next() {
		var i Conjunction
		if err := rows.Scan(
			&i.ID,
			&i.Lemma,
			&i.Type,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateConjunctions = `-- name: TruncateConjunctions :exec
TRUNCATE conjunctions RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateConjunctions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateConjunctions)
	return err
}
