// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: determiners.sql

package store

import (
	"context"
)

const insertDeterminer = `-- name: InsertDeterminer :exec
INSERT INTO determiners (lemma, type, number)
VALUES ($1, $2, $3)
`

type InsertDeterminerParams struct {
	Lemma  string `db:"lemma" json:"lemma"`
	Type   string `db:"type" json:"type"`
	Number string `db:"number" json:"number"`
}

func (q *Queries) InsertDeterminer(ctx context.Context, arg InsertDeterminerParams) error {
	_, err := q.db.Exec(ctx, insertDeterminer, arg.Lemma, arg.Type, arg.Number)
	return err
}

const listDeterminers = `-- name: ListDeterminers :many
SELECT id, lemma, type, number, active FROM determiners
ORDER BY lemma
`

func (q *Queries) ListDeterminers(ctx context.Context) ([]Determiner, error) {
	rows, err := q.db.Query(ctx, listDeterminers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Determiner
	for rows.Next() {
		var i Determiner
		if err := rows.Scan(
			&i.ID,
			&i.Lemma,
			&i.Type,
			&i.Number,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateDeterminers = `-- name: TruncateDeterminers :exec
TRUNCATE determiners RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateDeterminers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateDeterminers)
	return err
}
