// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nouns.sql

package store

import (
	"context"
)

const countNouns = `-- name: CountNouns :one
SELECT COUNT(*) FROM nouns
`

func (q *Queries) CountNouns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNouns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNounByLemma = `-- name: GetNounByLemma :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural FROM nouns
WHERE lemma = $1
`

func (q *Queries) GetNounByLemma(ctx context.Context, lemma string) (Noun, error) {
	row := q.db.QueryRow(ctx, getNounByLemma, lemma)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
	)
	return i, err
}

const getRandomNoun = `-- name: GetRandomNoun :one
SELECT id, lemma, inflections, source, source_id, register, frequency, active, vote_count, create_time, update_time, plural FROM nouns
WHERE active
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomNoun(ctx context.Context) (Noun, error) {
	row := q.db.QueryRow(ctx, getRandomNoun)
	var i Noun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Inflections,
		&i.Source,
		&i.SourceID,
		&i.Register,
		&i.Frequency,
		&i.Active,
		&i.VoteCount,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Plural,
	)
	return i, err
}

const insertNoun = `-- name: InsertNoun :exec
INSERT INTO nouns (lemma, inflections, source)
VALUES ($1, $2, $3)
ON CONFLICT (lemma, source) DO NOTHING
`

type InsertNounParams struct {
	Lemma       string `db:"lemma" json:"lemma"`
	Inflections []byte `db:"inflections" json:"inflections"`
	Source      string `db:"source" json:"source"`
}

func (q *Queries) InsertNoun(ctx context.Context, arg InsertNounParams) error {
	_, err := q.db.Exec(ctx, insertNoun, arg.Lemma, arg.Inflections, arg.Source)
	return err
}

const markPluralNouns = `-- name: MarkPluralNouns :execrows
UPDATE nouns p SET plural = TRUE
WHERE p.lemma ~ 's$'
  AND length(p.lemma) > 3
  AND p.lemma !~ '(ss|us|is)$'
  AND EXISTS (SELECT 1 FROM nouns n WHERE n.lemma = left(p.lemma, -1))
`

// A lemma is plural if it ends in -s and its singular is also a lemma
// ("Rastas"/"Rasta"). Short words and -ss/-us/-is endings ("Ms", "Mass",
// "Pus") are left singular.
func (q *Queries) MarkPluralNouns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markPluralNouns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const truncateNouns = `-- name: TruncateNouns :exec
TRUNCATE nouns RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateNouns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateNouns)
	return err
}
