// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prepositions.sql

package store

import (
	"context"
)

const insertPreposition = `-- name: InsertPreposition :exec
INSERT INTO prepositions (lemma)
VALUES ($1)
`

func (q *Queries) InsertPreposition(ctx context.Context, lemma string) error {
	_, err := q.db.Exec(ctx, insertPreposition, lemma)
	return err
}

const listPrepositions = `-- name: ListPrepositions :many
SELECT id, lemma, active FROM prepositions
ORDER BY lemma
`

func (q *Queries) ListPrepositions(ctx context.Context) ([]Preposition, error) {
	rows, err := q.db.Query(ctx, listPrepositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preposition
	for rows.Next() {
		var i Preposition
		if err := rows.Scan(&i.ID, &i.Lemma, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncatePrepositions = `-- name: TruncatePrepositions :exec
TRUNCATE prepositions RESTART IDENTITY CASCADE
`

func (q *Queries) TruncatePrepositions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncatePrepositions)
	return err
}
