// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pronouns.sql

package store

import (
	"context"
)

const getRandomPronounWithCase = `-- name: GetRandomPronounWithCase :one
SELECT id, lemma, case_, person, number, gender, active FROM pronouns
WHERE active AND case_ = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomPronounWithCase(ctx context.Context, case_ string) (Pronoun, error) {
	row := q.db.QueryRow(ctx, getRandomPronounWithCase, case_)
	var i Pronoun
	err := row.Scan(
		&i.ID,
		&i.Lemma,
		&i.Case,
		&i.Person,
		&i.Number,
		&i.Gender,
		&i.Active,
	)
	return i, err
}

const insertPronoun = `-- name: InsertPronoun :exec
INSERT INTO pronouns (lemma, case_, person, number, gender)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPronounParams struct {
	Lemma  string `db:"lemma" json:"lemma"`
	Case   string `db:"case_" json:"case_"`
	Person int16  `db:"person" json:"person"`
	Number string `db:"number" json:"number"`
	Gender string `db:"gender" json:"gender"`
}

func (q *Queries) InsertPronoun(ctx context.Context, arg InsertPronounParams) error {
	_, err := q.db.Exec(ctx, insertPronoun,
		arg.Lemma,
		arg.Case,
		arg.Person,
		arg.Number,
		arg.Gender,
	)
	return err
}

const listPronouns = `-- name: ListPronouns :many
SELECT id, lemma, case_, person, number, gender, active FROM pronouns
ORDER BY lemma, case_, person, number, gender
`

func (q *Queries) ListPronouns(ctx context.Context) ([]Pronoun, error) {
	rows, err := q.db.Query(ctx, listPronouns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pronoun
	for rows.Next() {
		var i Pronoun
		if err := rows.Scan(
			&i.ID,
			&i.Lemma,
			&i.Case,
			&i.Person,
			&i.Number,
			&i.Gender,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncatePronouns = `-- name: TruncatePronouns :exec
TRUNCATE pronouns RESTART IDENTITY CASCADE
`

func (q *Queries) TruncatePronouns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncatePronouns)
	return err
}
