// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountAdjectives(ctx context.Context) (int64, error)
	CountAdverbs(ctx context.Context) (int64, error)
	CountNouns(ctx context.Context) (int64, error)
	CountVerbs(ctx context.Context) (int64, error)
	GetAdjectiveByLemma(ctx context.Context, lemma string) (Adjective, error)
	GetAdverbByLemma(ctx context.Context, lemma string) (Adverb, error)
	GetNounByLemma(ctx context.Context, lemma string) (Noun, error)
	GetRandomAdjective(ctx context.Context) (Adjective, error)
	GetRandomAdverb(ctx context.Context) (Adverb, error)
	GetRandomConjunction(ctx context.Context) (Conjunction, error)
	GetRandomConjunctionOfType(ctx context.Context, type_ string) (Conjunction, error)
	GetRandomDeterminer(ctx context.Context) (Determiner, error)
	GetRandomDeterminerWithNumber(ctx context.Context, numbers []string) (Determiner, error)
	GetRandomNPConjunction(ctx context.Context) (Conjunction, error)
	GetRandomNoun(ctx context.Context) (Noun, error)
	GetRandomPreposition(ctx context.Context) (Preposition, error)
	GetRandomPronounWithCase(ctx context.Context, case_ string) (Pronoun, error)
	GetRandomVerb(ctx context.Context) (Verb, error)
	GetRandomVerbWithFrame(ctx context.Context, frame string) (Verb, error)
	GetVerbByLemma(ctx context.Context, lemma string) (Verb, error)
	InsertAdjective(ctx context.Context, arg InsertAdjectiveParams) error
	InsertAdverb(ctx context.Context, arg InsertAdverbParams) error
	InsertConjunction(ctx context.Context, arg InsertConjunctionParams) error
	InsertDeterminer(ctx context.Context, arg InsertDeterminerParams) error
	InsertNoun(ctx context.Context, arg InsertNounParams) error
	InsertPreposition(ctx context.Context, lemma string) error
	InsertPronoun(ctx context.Context, arg InsertPronounParams) error
	InsertVerb(ctx context.Context, arg InsertVerbParams) error
	ListConjunctions(ctx context.Context) ([]Conjunction, error)
	ListDeterminers(ctx context.Context) ([]Determiner, error)
	ListPrepositions(ctx context.Context) ([]Preposition, error)
	ListPronouns(ctx context.Context) ([]Pronoun, error)
	// A lemma is plural if it ends in -s and its singular (minus -s, or minus
	// -es) is also a lemma ("Rastas"/"Rasta", "eyeglasses"/"eyeglass"). Short
	// words and -ss/-us/-is endings ("Ms", "Mass", "Pus") are left singular.
	MarkPluralNouns(ctx context.Context) (int64, error)
	TruncateAdjectives(ctx context.Context) error
	TruncateAdverbs(ctx context.Context) error
	TruncateConjunctions(ctx context.Context) error
	TruncateDeterminers(ctx context.Context) error
	TruncateNouns(ctx context.Context) error
	TruncatePrepositions(ctx context.Context) error
	TruncatePronouns(ctx context.Context) error
	TruncateVerbs(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
